#!/usr/bin/env node

const fs = require("fs");
const path = require("path");

// --- Configuration ---
const SCAN_EXTENSIONS = [
  ".js", ".ts", ".jsx", ".tsx", ".mjs", ".cjs", ".vue", ".svelte",
];
const IGNORE_DIRS = [
  "node_modules", ".git", "dist", "build", ".next", ".nuxt",
  "coverage", ".turbo", ".cache",
];
const ENV_PATTERN = /process\.env\.([A-Z_][A-Z0-9_]*)/g;
const IMPORT_META_PATTERN = /import\.meta\.env\.([A-Z_][A-Z0-9_]*)/g;

// --- Helpers ---
function getAllFiles(dirPath, files = []) {
  const entries = fs.readdirSync(dirPath, { withFileTypes: true });

  for (const entry of entries) {
    if (IGNORE_DIRS.includes(entry.name)) continue;

    const fullPath = path.join(dirPath, entry.name);

    if (entry.isDirectory()) {
      getAllFiles(fullPath, files);
    } else if (SCAN_EXTENSIONS.includes(path.extname(entry.name))) {
      files.push(fullPath);
    }
  }

  return files;
}

function scanFile(filePath) {
  const content = fs.readFileSync(filePath, "utf-8");
  const results = [];

  for (const pattern of [ENV_PATTERN, IMPORT_META_PATTERN]) {
    pattern.lastIndex = 0;
    let match;
    while ((match = pattern.exec(content)) !== null) {
      const line = content.substring(0, match.index).split("\n").length;
      results.push({
        varName: match[1],
        file: filePath,
        line,
      });
    }
  }

  return results;
}

// --- Main ---
function main() {
  const targetDir = process.argv[2] || ".";
  const resolvedDir = path.resolve(targetDir);

  if (!fs.existsSync(resolvedDir)) {
    console.error(`\x1b[31mError: Directory "${resolvedDir}" does not exist.\x1b[0m`);
    process.exit(1);
  }

  console.log(`\n🔍 Scanning: ${resolvedDir}\n`);

  const files = getAllFiles(resolvedDir);
  const allFinds = [];

  for (const file of files) {
    const finds = scanFile(file);
    allFinds.push(...finds);
  }

  if (allFinds.length === 0) {
    console.log("No process.env or import.meta.env references found.");
    return;
  }

  // Group by variable name
  const envMap = new Map();
  for (const find of allFinds) {
    if (!envMap.has(find.varName)) {
      envMap.set(find.varName, []);
    }
    envMap.get(find.varName).push({ file: find.file, line: find.line });
  }

  // Sort alphabetically
  const sorted = [...envMap.entries()].sort((a, b) => a[0].localeCompare(b[0]));

  // Print report
  console.log(`Found \x1b[36m${sorted.length}\x1b[0m unique env variables across \x1b[36m${files.length}\x1b[0m files:\n`);
  console.log("─".repeat(60));

  for (const [varName, locations] of sorted) {
    console.log(`\n  \x1b[33m${varName}\x1b[0m`);
    for (const loc of locations) {
      const relPath = path.relative(resolvedDir, loc.file);
      console.log(`    \x1b[90m→ ${relPath}:${loc.line}\x1b[0m`);
    }
  }

  console.log("\n" + "─".repeat(60));

  // Check for existing .env file to pre-fill values
  const existingEnv = {};
  const envFilePath = path.join(resolvedDir, ".env");
  if (fs.existsSync(envFilePath)) {
    const envContent = fs.readFileSync(envFilePath, "utf-8");
    for (const line of envContent.split("\n")) {
      const match = line.match(/^([A-Z_][A-Z0-9_]*)=/);
      if (match) {
        existingEnv[match[1]] = "# value exists in .env";
      }
    }
  }

  // Generate .env.example
  const exampleLines = [
    "# ============================================",
    "# Environment Variables",
    `# Auto-generated by scan-env.js on ${new Date().toISOString().split("T")[0]}`,
    "# ============================================",
    "",
  ];

  for (const [varName, locations] of sorted) {
    const files = locations.map((l) => path.relative(resolvedDir, l.file));
    const uniqueFiles = [...new Set(files)];
    exampleLines.push(`# Used in: ${uniqueFiles.join(", ")}`);
    exampleLines.push(`${varName}=`);
    exampleLines.push("");
  }

  const examplePath = path.join(resolvedDir, ".env.example");
  fs.writeFileSync(examplePath, exampleLines.join("\n"), "utf-8");
  console.log(`\n✅ Generated \x1b[32m.env.example\x1b[0m with ${sorted.length} variables`);
  console.log(`   ${examplePath}\n`);
}

main();
